### ISSUE TITLE
Replace legacy beacon with beacon 2.0

### ISSUE THREAD

**Issue by omarreiss** [Yoast/wp-helpscout#13]
Support for legacy Beacons will be coming to an end on December 5, 2019. 

We need to make sure we update our helpscout beacon before that time.

https://docs.helpscout.com/article/1364-updates-to-legacy-beacon?utm_source=hubspot&utm_source=hs_automation&utm_medium=email&utm_medium=email&utm_campaign=messages&utm_campaign=Messages&utm_content=76463836&_hsenc=p2ANqtz--CDkWGTftc2wVsaGWgGgfvuhTP33FjQvs0lD-kI4lKcguARerYfXgNSajhJfPR9Hn970e2NFuFt2NNbIhiDfv02qbc8Q&_hsmi=76463836

**Comment by IreneStr** [comment]
More context: this is used in Video, Local, News and Woo.
Support will create new beacons in the HelpScout admin and share the code snippets soon.

**Comment by herregroen** [comment]
With the new HelpScout Beacon API that's almost entirely configured within helpscout itself this library is no longer required. Once we've removed it from all plugins a new issue should be created here to deprecate this library.
