### ISSUE TITLE
Plugin adding helpscout beacon adds it on all wpseo settings pages.

### ISSUE THREAD

**Issue by omarreiss** [Yoast/wp-helpscout#4]
And it shouldn't...

**Comment by atimmer** [comment]
Fixed by https://github.com/Yoast/wpseo-woocommerce/pull/124, https://github.com/Yoast/wpseo-news/pull/220, https://github.com/Yoast/wordpress-seo-local/pull/543 and https://github.com/Yoast/wpseo-video/pull/266
