### ISSUE TITLE
PHP segfault in class-helpscout-beacon-identifier

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/wp-helpscout#8]
In the `class-helpscout-beacon-identifier` there are parameters added to the `php_uname( )` function.

This causes a PHP segfault error in PHP 7.2.7. Removing the parameters solves the issue.

**Comment by moorscode** [comment]
This should be 2.0.4 - so branch from master and create a `hotfix/2.0.4` branch to base this PR on.

After changing the code, a release needs to be done for this tool.
The release needs to be updated in all plugins that has it as a dependency.

**Comment by moorscode** [comment]
I cannot find any reference to this problem on Google about the segfault error in PHP 7.2.7, could you add more context to this issue?

**Comment by moorscode** [comment]
Executing this code on a PHP Sandbox in 7.2.7, this does not throw any errors.
See https://3v4l.org/6EssW

**Comment by moorscode** [comment]
The expected functionality is not conforming to the details provided by the specs of this function:

> mode is a single character that defines what information is returned:
We are using a string with two values here.

But as this has been used for over two years, without any problems, changing it now for this reason alone does not seem like an efficient use of anybody's time and energy.

**Comment by CarolineGeven** [comment]
Stacktrace:
```
lstat("/www/wp-content/plugins/wordpress-seo-premium/vendor/yoast/wp-helpscout/src/class-helpscout-beacon-identifier.php", {st_mode=S_IFREG|0644, st_size=5153, ...}) = 0
open("/www/wp-content/plugins/wordpress-seo-premium/vendor/yoast/wp-helpscout/src/class-helpscout-beacon-identifier.php", O_RDONLY) = 8
fstat(8, {st_mode=S_IFREG|0644, st_size=5153, ...}) = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=5153, ...}) = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=5153, ...}) = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=5153, ...}) = 0
mmap(NULL, 5153, PROT_READ, MAP_SHARED, 8, 0) = 0x7f1ff0594000
open("/opcache/eb9aea4ec266f2ce9505e77cc280cae3/www/wp-content/plugins/wordpress-seo-premium/vendor/yoast/wp-helpscout/src/class-helpscout-beacon-identifier.php.bin", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/www/wp-content/plugins/wordpress-seo-premium/vendor/yoast/wp-helpscout/src/class-helpscout-beacon-identifier.php", {st_mode=S_IFREG|0644, st_size=5153, ...}) = 0
open("/www/wp-content/debug.log", O_WRONLY|O_CREAT|O_APPEND, 0644) = 9
write(9, "[05-Jul-2018 21:00:25 UTC] PHP Warning:  loadClass() has been disabled for security reasons in /www/wp-content/plugins/wordpress-seo-premium/vendor/composer/ClassLoader52.php on line 186\n", 187) = 187
close(9)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0} ---
+++ killed by SIGSEGV +++
```

> so a few things I was updated on is that we disable php_uname and we're using Opcache. When opcache is disabled it doesn't segfault. 
> Also, when we do see the segfault it's when visiting the admin section of Yoast
> guess to correct myself for "single argument over multiple" it's a single $mode rather than multiple. which we found referenced here - https://github.com/Yoast/wordpress-seo/issues/9235

**Comment by iamazik** [comment]
Please inform the customer of conversation # 435787 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 436101 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 438346 when this conversation has been closed.
